### ISSUE TITLE
shock_cache_get возвращает указатель на память в стеке

### ISSUE THREAD

**Issue by schdub** [MrOnlineCoder/shockd#3]
Нельзя возвращать указатель на буфер buf.
Подробнее о проблеме можно почитать например у Стефан К. Дьюхерст "Скользкие места С++", совет 66.

PS: это Ваш первый проект на C/С++?
PPS: То же самое относится к shock_date_now() и подобным если есть.

**Comment by MrOnlineCoder** [comment]
> PS: это Ваш первый проект на C/С++?

Не первый, но первый который я дал на тест на форуме.

> Нельзя возвращать указатель на буфер buf.

Тогда почему этот код работает?
